// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:95e2801d-ef80-4cc7-9c3e-6d8e2bc3ffd0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xV0YnvLFq",
    "aws_user_pools_web_client_id": "30tocs8nb1kh1l5gg9lohrbmj1",
    "aws_mobile_analytics_app_id": "aae3dadfecc94580ae33ccdcfbbe9f90",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
